package day4;     // Website : https://jsonplaceholder.typicode.com/


import static io.restassured.RestAssured.given;


import static org.hamcrest.Matchers.equalTo;

import org.testng.annotations.Test;



/* Sometimes when we send request then we can get response in json format or xml format.
So we should be able to verify different things in response not only cookies/headers/response code.
Along with these things we can validate the data type( jsone / xml)

NOTE : We will add required json dependencies.
NOTE : xml dependencies will come along with RestAssured. We don't need to add explicitly.

NOTE : We don't need to add json-schema validator here. As we are going to validate json data only
which comes in response.
*/


// Parsing = Each and everything we will validate

// NOTE : JSON file will always start with curly braces
/* Starts of an Array -> [
 * {
 *    This area/element between curly braces is a json object.
 * }
End of an Array -> [

*/

public class ParsingJSONResponse_1 {
	
	
	/* Approach 1 without storing response in any variable we will be able to perform only
	 several validations on Response */
	 // Approach 1
	
	@Test(priority=1)
	void testJSONResponse1()
	{
		
	given()
	.contentType("application/json")
	// .contentType("ContentType.JSON")  // -> Both are correct
	
	
	.when()
	.get("https://jsonplaceholder.typicode.com/users") // using request which has 10 records only
	
	  
	  .then()
	  .statusCode(200)
	  .header("Content-Type","application/json; charset=utf-8")  
	  .body("[0].email",equalTo("Sincere@april.biz"))
	  .body("[5].address.city",equalTo("South Christy"));
	  // will not take x generated by website Eg. x[5]
	    
	}
}
